### ISSUE TITLE
Request for New Release for Clojure 1.8.0

### ISSUE THREAD

**Issue by alan-wischmeyer-climate** [ifesdjeen/zweikopf#19]
With the change that was merged to update the Clojure dependency from 1.7.0 to 1.8.0, I would like to request a new release.

**Comment by ifesdjeen** [comment]
That makes sense, I'll cut a new release

**Comment by alan-wischmeyer-climate** [comment]
Thank you; your help is very much appreciated.

**Comment by ifesdjeen** [comment]
Version `1.0.2` released. 
Thanks for help!
